# Generated by Django 5.1.2 on 2024-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('registro', models.IntegerField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=100)),
                ('mes', models.PositiveSmallIntegerField()),
                ('produccionTotal', models.IntegerField()),
                ('cantidaPiezasConFallas', models.IntegerField()),
            ],
        ),
    ]
